### PR TITLE
Add SVT-HEVC, SVT-AV1, SVT-VP9

### PR DESCRIPTION
**Pull request by krakow10**
As a direct result of my github incompetency, #405 has commits that undo my changes in #404.
Thus, I present to you: #406

### CODE REVIEW

**Comment by rdp** [comment]
Is it ready for merge now you think?

**Comment by krakow10** [comment]
If you want to enable the SVT-HEVC codec, you can merge it now.  The SVT-HEVC codec that this enables by default works great and has no conflicts.  The commented out SVT-AV1 and SVT-VP9 bits will build an executable if individually enabled, but do not produce video output.  I don't have any more changes that I know how to make that will make them work better.

**Comment by rdp** [comment]
Mind testing it on a win32 build for me? Thanks.

**Comment by rdp** [comment]
Did you try a win32 build?

**Pull request merged**
