### PR TITLE
Added AVS2 codec.

### PR DESCRIPTION
**Pull request by xatabhk**
Enabled AVS2 codec.

### CODE REVIEW

**Comment by rdp** [comment]
Why not enabled in native?  Thanks!

**Comment by xatabhk** [comment]
> Why not enabled in native? Thanks!
Just to be on the safe side as I don’t know whether they can be complied on an Apple PC.

**Comment by rdp** [comment]
Any ideas on this one? https://github.com/rdp/ffmpeg-windows-build-helpers/issues/474

**Comment by xatabhk** [comment]
> Any ideas on this one? #474
The assembly code does not compile in win32 mode. I will create another pull to fix the issue.

**Pull request merged**
