### PR TITLE
Delete LICENSE

### PR DESCRIPTION
**Pull request by konyzulphrea**

### CODE REVIEW

**Comment by rdp** [comment]
was this intentional?

**Comment by konyzulphrea** [comment]
I'm afraid it is an accident. I also have been testing how the application should be performed. You may check my tuning.

**Comment by rdp** [comment]
did you find any tuning that helped?

**Comment by konyzulphrea** [comment]
Let me see, rdp. 

The being is about which functions should be put in since ffmpeg contains many parts which makes most of people feeling puzzled.

The tuning is about tailoring the needs since ffmpeg contains a library from basic to the most professional. The range may be too wide for some simple tasks.

I used to simulate the thing ensuring no junk included.
For example, To decide a Badaboom-like video transcoder

I have to study client's style first to provide the most suitable options such as mpegts demuxer, mkv demuxer, ac3 demuxer, ac3 decoder, aac decoder, mpeg2 decoder, x264 decoder, x264 10-bit, 12-bit vp9, mkv muxer, flac encoder, opus encoder, such of things. There are many things dropped. 

May I ask one thing right now? Have you been testing with AV1 codec? I like to know some result.

**Comment by hydra3333** [comment]
> Have you been testing with AV1 codec? 
I'd be interested in that too.  
Although AFAIK it's not integrated into ffmpeg as yet, I have been playing with building it based on jb's windows script and (being a dummy) haven't jagged a successful build.

**Comment by konyzulphrea** [comment]
(AV1) Isn't as simple as adding x264 encoder, opus codec into the ffmpeg ? Since ffmpeg is using the *nix workflow instead of windows workflow. I think you better try using linux cross compiling to try adding.

I was using virtual computer to do the thing, with windows 10 pro 64-bit , In most of cases, I only need to use the ubuntu bash to do most of my thing.

**Comment by rdp** [comment]
Looks like AV1 isn't "finalized" yet as a codec, and I also don't see an
ffmpeg plugin for it yet.

**Pull request closed without merging**
