### PR TITLE
Create cross_ffmpeg_compile_20170830.sh

### PR DESCRIPTION
**Pull request by konyzulphrea**
Sample for disabling old encoders,  enabling windows native api for hwaccels

### CODE REVIEW

**Comment by rdp** [comment]
what does "old" encoders mean here? It might be nicer to have it as an option on the real file so that differences are easier to spot :)

**Comment by schmidthubert** [comment]
All I see is --disable --disable --disable ????????? What's going on???? May I suggest you stick with your own build and not ruin rdp's script??? :confused:

>windows native api for hwaccels

Maybe you should read something for a while first BEFORE you even touch anything here ??? :unamused: 

The idea here is to stuff AS MUCH AS POSSIBLE into a static exe, what you do is AS LITTLE. Are you running on an i286 maybe??? :astonished:

**Comment by konyzulphrea** [comment]
This depends on codec's efficiency and output quality. May I ask you one
thing again? What is the motivation to construct the semi-auto script?
Quality.

So I write few lines for quality. I smith the finest one as Zeranoe has
provided a general one.

2017年8月30日 下午11:58，"Roger Pack" <notifications@github.com>寫道：

what does "old" encoders mean here? It might be nicer to have it as an
option on the real file so that differences are easier to spot :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rdp/ffmpeg-windows-build-helpers/pull/255#issuecomment-326036907>,
or mute the thread

**Comment by konyzulphrea** [comment]
absolutely not. I have my own ideas. I also have my own forked, only put
tested one for reviewing.

2017年8月31日 上午12:42，"Schmidt, Hubert" <notifications@github.com>寫道：

**Comment by rdp** [comment]
I'll check it out sometime, thanks!

**Comment by konyzulphrea** [comment]
Gentlemen and Ladies, I have found a new trick now x265 encoder can have main12 instead of main10 for people's concerns.

To run the program, you need windows 64-bit OS to execute it since I have enabled the profile while 10-bit is still possible for 32-bit OS.

For the details, it is welcomed to visit
https://github.com/konyzulphrea/ffmpeg-windows-build-helpers/tree/20170831

for further details after I have found there is one statement missing to make not so perfect. Why VP9 is automatically set to 12-bit but x265 can't?

**Comment by konyzulphrea** [comment]
I personally have figured why we only are able to output 10-bit x265, 10-bit x264 and 12-bit vp9 instead of 12-bit x265, 10-bit x264 and 12-bit vp9

According to https://github.com/konyzulphrea/IFME/blob/master/sources/build-x265_msys.sh , We should use -DMAIN12=ON to provide the maximum. 

The details can be studied from my release with a tag of 666

**Comment by konyzulphrea** [comment]
rdp, I think I have figured how to deal with at least one crappy problem for 64-bit Windows OS.

Why there is only 10-bit x265 produced but 12-bit vp9 generated successful? I have studied from other people, Can refer my re-constructed fork, but the configuration in release is only for windows 64-bit, I'm sorry.

**Pull request closed without merging**
