### PR TITLE
12-bit x265, how to make?

### PR DESCRIPTION
**Pull request by LEETUMBRA**
In short, in line 1291, using something like cmake_params+=" -DHIGH_BIT_DEPTH=1 -DMAIN12=ON"  instead of cmake_params+=" -DHIGH_BIT_DEPTH=1"  then you shall get the 12-bit x265, I have tried that, outstanding.

For the infomation, You can refer https://github.com/konyzulphrea/IFME/blob/master/sources/build-x265_msys.sh

### CODE REVIEW

**Comment by schmidthubert** [comment]
x265 multibit exe is to find in DeadSix27's CC script line 1733 

https://github.com/DeadSix27/python_cross_compile_script/blob/master/cross_compiler.py

**Comment by konyzulphrea** [comment]
It doesn't need the special thing first.

I suggest people starting from bash first, then python later...

**Comment by ValZapod** [comment]
While there maybe activate HDR10+ support? https://bitbucket.org/multicoreware/x265/issues/336/multilibsh-enable-dynamic-hdr10-support

**Comment by rdp** [comment]
Good news, 12bit was added recently, thanks for the suggestion.

**Comment by ValZapod** [comment]
@rdp What about HDR10+)) See above.

**Comment by rdp** [comment]
That was added as well AFAICT :)

**Comment by rdp** [comment]
Thanks @PeacefullyDisturbed :)

**Pull request closed without merging**
