### PR TITLE
Make script executable

### PR DESCRIPTION
**Pull request by AnimMouse**
Fixes

`./cross_compile_ffmpeg.sh: Permission denied`

### CODE REVIEW

**Comment by rdp** [comment]
Hmm trying to figure out how this ever worked...

**Comment by marierose147** [comment]
Just `chmod +x cross_compile_ffmpeg.sh`

**Comment by AnimMouse** [comment]
I just did `git add --chmod=+x cross_compile_ffmpeg.sh` because it is [failing](https://github.com/AnimMouse/ffmpeg-autobuild/actions/runs/201833326) when I'm running it in my GitHub Actions.

P.S. The commit eaa31e8 is the one that removed the executable mode.

**Comment by AnimMouse** [comment]
@marierose147 It's better if you make it executable on Git instead of doing it on your computer.

**Comment by rdp** [comment]
Thanks!

**Comment by AnimMouse** [comment]
Thanks!

**Pull request merged**
