### PR TITLE
build libaom before libx264 in case of build with libav

### PR DESCRIPTION
**Pull request by AndCycle**
minor fix of build order

### CODE REVIEW

**Comment by AndCycle** [comment]
@hydra3333 because libx264 do build ffmpeg in certain case, 
if libaom doesn't build before it this will result in missing package

**Comment by hydra3333** [comment]
ok. To confirm, are you saying libx264 depends on libaom ?

**Comment by AndCycle** [comment]
@hydra3333 
nope, to be accurate, it's ffmpeg depend on libaom,

but libx264 do build ffmpeg in this line
https://github.com/rdp/ffmpeg-windows-build-helpers/blob/f8ab990f7ad91eb4f50cef3b4cfb2ba5341d67a2/cross_compile_ffmpeg.sh#L1351

**Comment by hydra3333** [comment]
ah. thank you.  it's the pre-x264 build

**Pull request merged**
