### PR TITLE
insecure connections

### PR DESCRIPTION
**Pull request by vookimedlo**
It was found that some downloads namely from the sourceforge cannot be
completed because the connection is not secure from the curl point of
view.

This could worked-around by allowing insecure connection (-k option).

Increasing the xz version to the 5.2.3 (from 5.2.2)

### CODE REVIEW

**Comment by rdp** [comment]
Yeah I've run into this before and we determined it was some kind of
certificate failure on the client side...hmm...I'd be down with a patch
that replaces all uses of curl with wget maybe [?]

**Comment by DeadSix27** [comment]
@rdp its part of the big PR im working on, you can rip it out of there:

code here: 
https://github.com/DeadSix27/ffmpeg-windows-build-helpers/commit/847998e4e188614419d49ee8662341165db7704a#diff-6aa78e200c567e3c5cf63806768b2be3R428
config here:
https://github.com/DeadSix27/ffmpeg-windows-build-helpers/commit/847998e4e188614419d49ee8662341165db7704a#diff-6aa78e200c567e3c5cf63806768b2be3R12

**Comment by rdp** [comment]
I'll just wait for the big PR :)

**Comment by rdp** [comment]
OK it seems to be working OK without -k these days, thanks for your help!

**Pull request closed without merging**
