### PR TITLE
XP support for x265 64 bit

### PR DESCRIPTION
**Pull request by mikemyers9**
XP support for x265 64 bit

### CODE REVIEW

**Comment by DeadSix27** [comment]
Does the lack of "-DWINXP_SUPPORT:BOOL=TRUE" during 64bit-compilation enable winXP support in 64bit?
(thats what that change does)
Before:
x265 will always have: -DWINXP_SUPPORT:BOOL=TRUE
After:
x265 will only have -DWINXP_SUPPORT:BOOL=TRUE in 32bit.

**Comment by rdp** [comment]
Did the old way not work for you?

**Comment by mikemyers9** [comment]
It removes "XP support for x265 64 bit" ^^
As it seem pointless.

**Comment by DeadSix27** [comment]
@mikemyers9 https://en.wikipedia.org/wiki/Windows_XP_editions#Windows_XP_64-Bit_Edition
XP has 64bit. Why is it pointless.
With that logic XP is pointless (which it is :P) but ye.

**Comment by mikemyers9** [comment]
to avoid adding extra burden on 99.999~% uses which are not XP when using 64 bit

**Comment by rdp** [comment]
So do you have/need this for an XP 64 bit box?

**Comment by mirh** [comment]
Putting aside this needs rebasing

Why not just making this a question for the user "which minimum Windows version do you care"?
Way less random wondering

**Comment by rdp** [comment]
I think this was satisfied out of band, if not please comment here, thanks!

**Pull request closed without merging**
