### PR TITLE
Fix x265 3.6 x86 asm optimization

### LINKED ISSUE #599: x265 will build 32bit on x64
Hi

I used this command `./cross_compile_ffmpeg.sh --disable-nonfree=n --prefer-stable=n` and chose `3. Win64 (64-bit only)`
The build process completed without error, but the CLI shows that the built x265 (x265.exe and libx265 of ffmpeg) is 32 bit.

```
PS D:\bin\ffmpeg\git_20211212> ./x265 -h
x265 [info]: HEVC encoder version 3.5+20-17839cc0dv
x265 [info]: build info [Windows][GCC 10.2.0][32 bit][noasm] 8bit+10bit+12bit
```

```
PS D:\bin\ffmpeg\git_20211212> ./ffmpeg -i ./in.mp4 -c:v libx265 ./out.mp4
ffmpeg version N-104861-g7fe5c7f02d-ffmpeg-windows-build-helpers Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (GCC)
  configuration: --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-liblensfun --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libaom --enable-libvpx --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags='-mtune=generic' --extra-cflags=-O3 --enable-static --disable-shared --prefix=/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree --enable-libfdk-aac --enable-decklink
  libavutil      57. 11.100 / 57. 11.100
  libavcodec     59. 14.100 / 59. 14.100
  libavformat    59. 10.100 / 59. 10.100
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8. 20.100 /  8. 20.100
  libswscale      6.  1.101 /  6.  1.101
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './in.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:21.06, start: 0.000000, bitrate: 290 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, progressive), 512x288, 156 kb/s, 23.98 fps, 23.98 tbr, 24k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> hevc (libx265))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
x265 [info]: HEVC encoder version 3.5+20-17839cc0d
x265 [info]: build info [Windows][GCC 10.2.0][32 bit][noasm] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: none!
x265 [info]: Main profile, Level-2.1 (Main tier)
```

Both executables were copied from `ffmpeg-windows-build-helpers \ sandbox \ win64`, so I don't think I chose 32 bit ...
If I change to `--prefer-stable=y` ,then build 64 bit correctly. (bit old revision)
WSL2+Ubuntu 20.04 issue?

### LINKED ISSUE #681: FFMPEG x265 non-stable (master branch) resolution suggestion...
When I compiled the FFMPEG, without using the "stable=y" option, and therefore, the "stable=n" option, it resulted in x265 not using any cpu capabilities. I believe I know the problem and resolution. I had the same problem, the first time I compiled x265, from multicoreware, and resolved it, with that x265 CLI. The problem was that I needed to have the following in the cmake file... I adapted what was on multicoreware's website, to my own computer setup, so options for it to autodetect, or select it somehow, would need to be considered, in the script, to be suitable for those with different configurations...

>>>
#!cmake

# specify processor type
SET(CMAKE_SYSTEM_PROCESSOR amd64)

# this one is important
SET(CMAKE_SYSTEM_NAME Windows)

# specify the cross compiler
SET(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
SET(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)
SET(CMAKE_ASM_YASM_COMPILER yasm)

SET(CMAKE_CXX_FLAGS "-static-libgcc -static-libstdc++ -static -march=znver2 -O2 -mtune=znver2 -O2 -s")
SET(CMAKE_C_FLAGS "-static-libgcc -static-libstdc++ -static -march=znver2 -O2 -mtune=znver2 -O2 -s")
SET(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "-static-libgcc -static-libstdc++ -static -march=znver2 -O2 -mtune=znver2 -O2 -s")
SET(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS "-static-libgcc -static-libstdc++ -static -march=znver2 -O2 -mtune=znver2 -O2 -s")
<<<

### LINKED ISSUE #736: Issue with x265 3.6 x86 asm optimization
Hello there, i found an issue.
when i use this script build ffmpeg n7.0 win64 with x265 version 3.6, I can't enable x86 asm optimization (like this picture).
ffmpeg_7 0_x265_3 6_noasm
when i use this script build ffmpeg n7.0 win64 with x265 version 3.5, I can enable x86 asm optimization (like this picture).
ffmpeg_7 0_x265_3 5_asm

### PR DESCRIPTION
**Pull request by AnimMouse**
Fix x265 3.6 x86 asm optimization by adding a patch that restore this line `if("${SYSPROC}" STREQUAL "" OR X86MATCH GREATER "-1")` in CMakeLists.txt.
Fixes #736, fixes #681, fixes #599, fixes https://github.com/AnimMouse/ffmpeg-stable-autobuild/issues/131.

Master:
```sh
ffmpeg version git-2024-05-04-38f67a3-ffmpeg-windows-build-helpers Copyright (c) 2000-2024 the FFmpeg developers
x265 [info]: HEVC encoder version 3.6+1-2f95fe7c8
x265 [info]: build info [Windows][GCC 10.2.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
```

Release 7.0:
```sh
ffmpeg version n7.0-ffmpeg-windows-build-helpers Copyright (c) 2000-2024 the FFmpeg developers
x265 [info]: HEVC encoder version 3.6+1-2f95fe7c8
x265 [info]: build info [Windows][GCC 10.2.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
```

### CODE REVIEW

**Comment by rdp** [comment]
thanks

**Comment by rdp** [comment]
A bug report upstream might be nice here too, or if not I might get to it someday :)

**Comment by AnimMouse** [comment]
@rdp As of [ba57a46](https://github.com/BtbN/FFmpeg-Builds/commit/ba57a4697f1cb9c3eab43fc814eddc68053f5b53#diff-21a75787ac26a51e4d17cfcdc3bf1013335b990b9f2b3bc2a6ad833b93c66cd8) BtbN/FFmpeg-Builds started using x265 version 3.6, and it did not cause any problems in their build script, I wonder maybe if this problem is related to this build script, or somewhere around the compilers that this build script uses.

**Comment by rdp** [comment]
is that older so still working?

**Comment by AnimMouse** [comment]
@rdp No, they are using the new one, the one that uses `if(X86MATCH GREATER "-1")` in the CMakeLists.txt, and their x265 build script is working properly with ASM.

**Pull request merged**
